config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'briefings#index'
  resources :briefings
  resources :bots
  resources :feeds do
    get 'logs/', to: 'feed_logs#index'
    get 'logs/:id', to: 'feed_logs#show'
  end
  devise_for :users
  devise_scope :user do
    authenticated :user do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
end

app/models/feed.rb
class Feed < ApplicationRecord
  has_and_belongs_to_many :briefing
  has_many :feed_logs
  alias_attribute :logs, :feed_logs

  def get_entries
    xml = HTTParty.get(url).body
    Feedjira.parse(xml).entries.each do |_entry|
      next if logs.where(published_at: _entry.published).exists?

      logs.create(
        title: _entry.title,
        url: _entry.url,
        summary: _entry.summary,
        published_at: _entry.published
      )
    end
  end

  def to_s
    @name
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_feed, only: %i[show edit update destroy]

  # GET /feeds or /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1 or /feeds/1.json
  def show; end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit; end

  # POST /feeds or /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1 or /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1 or /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_feed
    @feed = Feed.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def feed_params
    params.require(:feed).permit(:url, :name)
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_with(model: feed) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
        <% feed.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_area :url %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>

      <ul>
    <% @feeds.each do |feed| %>
      <li><a href="<%= feed.url %>"><%= feed.name %></a><br>
        <%= link_to 'Show', feed %>
        <%= link_to 'Edit', edit_feed_path(feed) %>
        <%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %>
      </li>
    <% end %>
      </ul>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @feed.url %>
</p>

<p>
  <strong>Name:</strong>
  <%= @feed.name %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>