config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'briefings#index'
  resources :briefings
  resources :bots
  resources :feeds do
    get 'logs/', to: 'feed_logs#index'
    get 'logs/:id', to: 'feed_logs#show'
  end
  devise_for :users
  devise_scope :user do
    authenticated :user do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
end

app/models/bot.rb
class Bot < ApplicationRecord
  has_and_belongs_to_many :briefing
  belongs_to :user

  include Rails.application.routes.url_helpers
  def publish(_brieifng_name, _feed_log)
    url = "https://api.telegram.org/bot#{token}/sendMessage"
    # summary = Kramdown::Document.new(_feed_log.summary, html_to_native: true).to_kramdown
    feed_log_url = Rails.application.routes.url_helpers.url_for(controller: 'feed_logs', action: 'show',
                                                                feed_id: _feed_log.feed_id, id: _feed_log.id)
    text = "#{_feed_log.title}
url: #{_feed_log.url}
rss-tg url: #{feed_log_url}
briefing: #{_brieifng_name}"
    response = HTTParty.post(url, { body: { chat_id: chat_id, text: text } })
    logger.debug response
  end
end

app/controllers/bots_controller.rb
class BotsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bot, only: %i[show edit update destroy]

  # GET /bots or /bots.json
  def index
    @bots = Bot.all
  end

  # GET /bots/1 or /bots/1.json
  def show; end

  # GET /bots/new
  def new
    @bot = Bot.new
  end

  # GET /bots/1/edit
  def edit; end

  # POST /bots or /bots.json
  def create
    @bot = Bot.new(bot_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @bot.save
        format.html { redirect_to @bot, notice: 'Bot was successfully created.' }
        format.json { render :show, status: :created, location: @bot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bots/1 or /bots/1.json
  def update
    respond_to do |format|
      if @bot.update(bot_params)
        format.html { redirect_to @bot, notice: 'Bot was successfully updated.' }
        format.json { render :show, status: :ok, location: @bot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bots/1 or /bots/1.json
  def destroy
    @bot.destroy
    respond_to do |format|
      format.html { redirect_to bots_url, notice: 'Bot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bot
    @bot = Bot.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def bot_params
    params.require(:bot).permit(:name, :token, :chat_id)
  end
end

app/helpers/bots_helper.rb
module BotsHelper
end

app/views/bots/_form.html.erb
<%= form_with(model: bot) do |form| %>
  <% if bot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bot.errors.count, "error") %> prohibited this bot from being saved:</h2>

      <ul>
        <% bot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :token %>
    <%= form.text_field :token %>
  </div>

  <div class="field">
    <%= form.label :chat_id %>
    <%= form.number_field :chat_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bots/edit.html.erb
<h1>Editing Bot</h1>

<%= render 'form', bot: @bot %>

<%= link_to 'Show', @bot %> |
<%= link_to 'Back', bots_path %>

app/views/bots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bots</h1>

<ul>
  <% @bots.each do |bot| %>
    <li>
      <%= bot.name %><br>
      <%= link_to 'Show', bot %>
      <%= link_to 'Edit', edit_bot_path(bot) %>
      <%= link_to 'Destroy', bot, method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

<br>

<%= link_to 'New Bot', new_bot_path %>

app/views/bots/new.html.erb
<h1>New Bot</h1>

<%= render 'form', bot: @bot %>

<%= link_to 'Back', bots_path %>

app/views/bots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bot.name %>
</p>

<p>
  <strong>Token:</strong>
  <%= @bot.token %>
</p>

<%= link_to 'Edit', edit_bot_path(@bot) %> |
<%= link_to 'Back', bots_path %>