config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'briefings#index'
  resources :briefings
  resources :bots
  resources :feeds do
    get 'logs/', to: 'feed_logs#index'
    get 'logs/:id', to: 'feed_logs#show'
  end
  devise_for :users
  devise_scope :user do
    authenticated :user do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
end

app/models/briefing.rb
class Briefing < ApplicationRecord
  enum period: %i[hourly daily weekly monthly]
  has_and_belongs_to_many :feeds
  belongs_to :bot
  belongs_to :user

  def publish(_publish_at)
    logger.debug "processing: #{name} #{last_run_at}"
    offset = 1.hour if hourly?
    offset = 1.day if daily?
    offset = 1.week if weekly?
    offset = 1.month if monthly?

    new_next_run_at = next_run_at + offset * interval

    feeds.each do |_feed|
      logger.debug "working on #{_feed.name}"
      _feed.logs.where(published_at: last_run_at..next_run_at).each do |feed_log|
        bot.publish name, feed_log
      end
    end

    update(
      next_run_at: next_run_at + offset * interval,
      last_run_at: _publish_at
    )
  end
end

app/controllers/briefings_controller.rb
class BriefingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_briefing, only: %i[show edit update destroy]

  # GET /briefings or /briefings.json
  def index
    @briefings = Briefing.where(user_id: current_user.id)
  end

  # GET /briefings/1 or /briefings/1.json
  def show; end

  # GET /briefings/new
  def new
    @briefing = Briefing.new
  end

  # GET /briefings/1/edit
  def edit; end

  # POST /briefings or /briefings.json
  def create
    @briefing = Briefing.new(briefing_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @briefing.save
        format.html { redirect_to @briefing, notice: 'Briefing was successfully created.' }
        format.json { render :show, status: :created, location: @briefing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @briefing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /briefings/1 or /briefings/1.json
  def update
    respond_to do |format|
      if @briefing.update(briefing_params)
        format.html { redirect_to @briefing, notice: 'Briefing was successfully updated.' }
        format.json { render :show, status: :ok, location: @briefing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @briefing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /briefings/1 or /briefings/1.json
  def destroy
    @briefing.destroy
    respond_to do |format|
      format.html { redirect_to briefings_url, notice: 'Briefing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_briefing
    @briefing = Briefing.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def briefing_params
    params.require(:briefing).permit(:name, :bot_id, :period, :interval, :next_run_at,
                                     { feed_ids: [] })
  end
end

app/helpers/briefings_helper.rb
module BriefingsHelper
end

app/views/briefings/_form.html.erb
<%= form_with(model: briefing) do |form| %>
  <% if briefing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(briefing.errors.count, "error") %> prohibited this briefing from being saved:</h2>

      <ul>
        <% briefing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.collection_radio_buttons(:bot_id, Bot.all, :id, :name) %>
  </div>

  <div class="field">
    <%= form.collection_check_boxes(:feed_ids, Feed.all, :id, :name) %>
  </div>

  <div class="field">
    <%= form.select(:period, Briefing.periods.keys.map {|period| [period.titleize, period]}) %>
  </div>

  <div class="field">
    <%= form.label :interval %>
    <%= form.text_field :interval %>
  </div>

  <div class="field">
    <%= form.label :next_run_at %>
    <%= form.datetime_field :next_run_at, value: briefing.next_run_at or DateTime.new %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/briefings/edit.html.erb
<h1>Editing Briefing</h1>

<%= render 'form', briefing: @briefing %>

<%= link_to 'Show', @briefing %> |
<%= link_to 'Back', briefings_path %>

app/views/briefings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Briefings</h1>

<ul>
  <% @briefings.each do |briefing| %>
    <li>
      <%= briefing.name %><br>
      <%= link_to 'Show', briefing %>
      <%= link_to 'Edit', edit_briefing_path(briefing) %>
      <%= link_to 'Destroy', briefing, method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>
<br>

<%= link_to 'New Briefing', new_briefing_path %>

app/views/briefings/new.html.erb
<h1>New Briefing</h1>

<%= render 'form', briefing: @briefing %>

<%= link_to 'Back', briefings_path %>

app/views/briefings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @briefing.name %>
</p>

<p>
  <strong>Feeds:</strong>
  <ul>
    <% @briefing.feeds.each do |feed| %>
      <li><a href="<%= feed.url %>"><%= feed.name %></a></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_briefing_path(@briefing) %> |
<%= link_to 'Back', briefings_path %>